import type { LucideIcon } from "lucide-react";
import {
  Bot,
  BrainCircuit,
  Camera,
  Code2,
  Palette,
  SearchCheck,
  ShoppingBag,
  Sparkles,
  Target,
  WandSparkles,
} from "lucide-react";
import { SKILL_PROMPTS } from "@/lib/skillPrompts";

export type CollectionAssistant = {
  slug: string;
  name: string;
  description: string;
  date: string;
  model: string;
  modelId: string;
  accent: string;
  logoText: string;
  icon: LucideIcon;
  welcome: string;
  specializations: string[];
  restrictions: string[];
  skillPrompt?: string;
};

export const assistants: CollectionAssistant[] = [
  {
    slug: "brief-buddy",
    name: "Brief Buddy",
    description: "Turns rough ideas into clear prompts, task notes, and ready-to-send instructions.",
    date: "23/12/2025",
    model: "Loko AI 2.5 Flash",
    modelId: "google/gemini-2.5-flash",
    accent: "from-sky-500 to-cyan-400",
    logoText: "BB",
    icon: Bot,
    welcome: "Send me a rough idea and I will turn it into a clean brief, prompt, or task note.",
    specializations: ["Prompt writing", "Task notes", "Instructions", "Brief creation"],
    restrictions: ["Coding", "SEO", "Sales", "UI Reviews", "Image generation"],
    skillPrompt: SKILL_PROMPTS.briefBuddy,
  },
  {
    slug: "daily-druid",
    name: "LokoAI Assistant",
    description: "General AI assistant for planning, research, writing, and productivity support.",
    date: "30/12/2025",
    model: "Kimi K2.6",
    modelId: "moonshotai/kimi-k2.6:free",
    accent: "from-emerald-500 to-teal-400",
    logoText: "LA",
    icon: WandSparkles,
    welcome: "Tell me anything and I will help with planning, research, writing, or productivity.",
    specializations: ["General assistance", "Planning", "Research", "Writing", "Productivity"],
    restrictions: [],
    skillPrompt: SKILL_PROMPTS.lokoAi,
  },
  {
    slug: "stacksmith-pro",
    name: "Stacksmith Pro",
    description: "Plans production-ready Next.js, React, and Node.js builds from a single product idea.",
    date: "13/02/2026",
    model: "Qwen 3 Coder",
    modelId: "qwen/qwen3-coder:free",
    accent: "from-indigo-500 to-sky-500",
    logoText: "SP",
    icon: Code2,
    welcome: "Describe the product you want to build and I will shape the stack, pages, and core flow.",
    specializations: ["Next.js", "React", "Node.js", "TypeScript", "APIs", "Databases", "Full-stack architecture"],
    restrictions: ["UI/UX Design", "SEO", "Sales", "Image generation", "Video editing"],
    skillPrompt: SKILL_PROMPTS.stacksmithPro,
  },
  {
    slug: "prospect-pilot",
    name: "Prospect Pilot",
    description: "Finds lead angles, outreach hooks, and quick qualification notes for sales work.",
    date: "17/02/2026",
    model: "GPT-4o Mini",
    modelId: "openai/gpt-4o-mini",
    accent: "from-rose-500 to-orange-400",
    logoText: "PP",
    icon: Target,
    welcome: "Share your target customer and I will draft outreach angles and lead qualification notes.",
    specializations: ["Lead generation", "Outreach", "Cold emails", "Sales qualification"],
    restrictions: ["Coding", "UI Design", "SEO", "Image generation", "Product development"],
  },
  {
    slug: "pixel-planner",
    name: "Pixel Planner",
    description: "Shapes website sections, visual direction, and layout ideas for polished web pages.",
    date: "13/01/2026",
    model: "Trinity Large Thinking",
    modelId: "arcee-ai/trinity-large-thinking",
    accent: "from-fuchsia-500 to-violet-500",
    logoText: "PX",
    icon: Palette,
    welcome: "Tell me the page or product style and I will plan sections, layout, and visual direction.",
    specializations: ["UI Design", "UX Design", "Landing Pages", "Wireframes", "Design Systems"],
    restrictions: ["Coding", "SEO", "Sales", "Full-stack development", "Database design"],
    skillPrompt: SKILL_PROMPTS.frontendDesign,
  },
  {
    slug: "lens-prompt-lab",
    name: "Lens Prompt Lab",
    description: "Creates cleaner image and video prompts with camera angles, style notes, and negatives.",
    date: "29/01/2026",
    model: "Loko AI 2.5 Flash Image",
    modelId: "google/gemini-2.5-flash-image",
    accent: "from-amber-500 to-yellow-400",
    logoText: "LP",
    icon: Camera,
    welcome: "Give me the image or video idea and I will create a strong prompt with camera and style details.",
    specializations: ["Image prompts", "Video prompts", "Camera prompts", "Midjourney prompts", "Flux prompts"],
    restrictions: ["Coding", "SEO", "Sales", "Full-stack development", "Actual image generation"],
    skillPrompt: SKILL_PROMPTS.gptImage,
  },
  {
    slug: "tosh-companion",
    name: "Tosh Companion",
    description: "A personal assistant for quick drafts, simple research, and daily creative support.",
    date: "16/01/2026",
    model: "Kimi K2.6",
    modelId: "moonshotai/kimi-k2.6:free",
    accent: "from-cyan-500 to-blue-500",
    logoText: "TC",
    icon: Sparkles,
    welcome: "I can help with drafts, quick answers, and creative support. What should we work on?",
    specializations: ["Drafts", "Creative support", "Brainstorming", "Personal productivity"],
    restrictions: ["Coding", "SEO", "Sales", "Legal advice"],
  },
  {
    slug: "interface-inspector",
    name: "Interface Inspector",
    description: "Reviews screenshots and UI flows to spot confusing layouts, copy, and interaction gaps.",
    date: "14/01/2026",
    model: "GPT-4o Mini",
    modelId: "openai/gpt-4o-mini",
    accent: "from-slate-700 to-slate-500",
    logoText: "II",
    icon: BrainCircuit,
    welcome: "Send a UI issue or describe a screen and I will point out improvements clearly.",
    specializations: ["Screenshot review", "UI audits", "UX reviews", "Accessibility audits", "Conversion analysis"],
    restrictions: ["Coding implementation", "Backend design", "SEO", "Sales"],
    skillPrompt: SKILL_PROMPTS.interfaceInspector,
  },
  {
    slug: "commerce-studio",
    name: "Commerce Studio",
    description: "Generates product ad concepts, creative directions, and asset ideas for ecommerce campaigns.",
    date: "14/01/2026",
    model: "Loko AI 2.5 Flash",
    modelId: "google/gemini-2.5-flash",
    accent: "from-lime-500 to-emerald-500",
    logoText: "CS",
    icon: ShoppingBag,
    welcome: "Share your product and audience and I will create ecommerce ad concepts and asset ideas.",
    specializations: ["Ecommerce", "Product ads", "Marketing creatives", "Store content"],
    restrictions: ["Coding", "Backend development", "SEO strategy", "Legal/compliance"],
    skillPrompt: SKILL_PROMPTS.commerceStudio,
  },
  {
    slug: "search-signal",
    name: "Search Signal",
    description: "Drafts SEO briefs, keyword clusters, and page outlines with a sharper content angle.",
    date: "19/12/2025",
    model: "Loko AI 2.5 Flash",
    modelId: "google/gemini-2.5-flash",
    accent: "from-blue-500 to-indigo-500",
    logoText: "SS",
    icon: SearchCheck,
    welcome: "Tell me the topic or URL goal and I will draft an SEO brief with keywords and outline.",
    specializations: ["SEO", "Keyword research", "Topic clusters", "Meta descriptions", "Content strategy"],
    restrictions: ["Coding", "UI Design", "Paid ads", "Sales outreach"],
    skillPrompt: SKILL_PROMPTS.searchSignal,
  },
  {
    slug: "frontend-design",
    name: "Frontend Design",
    description: "Creates premium React, Next.js, Tailwind, shadcn/ui, and Framer Motion interfaces.",
    date: "03/06/2026",
    model: "Qwen 3 Coder",
    modelId: "qwen/qwen3-coder:free",
    accent: "from-violet-500 to-fuchsia-500",
    logoText: "FD",
    icon: Palette,
    welcome: "Describe the UI, landing page, or dashboard and I will design a premium responsive interface.",
    specializations: ["Frontend UI", "SaaS pages", "Dashboards", "React components", "Responsive design"],
    restrictions: ["Backend-only architecture", "SEO-only strategy", "Sales outreach"],
    skillPrompt: SKILL_PROMPTS.frontendDesign,
  },
  {
    slug: "fullstack-builder",
    name: "Fullstack Builder",
    description: "Plans and builds frontend, backend, APIs, auth, databases, and scalable app architecture.",
    date: "03/06/2026",
    model: "Qwen 3 Coder",
    modelId: "qwen/qwen3-coder:free",
    accent: "from-indigo-500 to-cyan-500",
    logoText: "FB",
    icon: Code2,
    welcome: "Tell me the app idea and I will plan the frontend, backend, APIs, auth, and database flow.",
    specializations: ["Full-stack development", "APIs", "Auth", "Database design", "Realtime systems"],
    restrictions: ["Image prompts", "SEO-only strategy", "Thumbnail concepts"],
    skillPrompt: SKILL_PROMPTS.fullstackBuilder,
  },
  {
    slug: "gpt-image",
    name: "GPT Image",
    description: "Creates cinematic image, poster, thumbnail, lighting, camera, and visual storytelling prompts.",
    date: "03/06/2026",
    model: "Loko AI 2.5 Flash Image",
    modelId: "google/gemini-2.5-flash-image",
    accent: "from-amber-500 to-orange-500",
    logoText: "GI",
    icon: Camera,
    welcome: "Describe the scene and I will craft a cinematic image prompt with camera, lighting, mood, and composition.",
    specializations: ["Cinematic prompts", "Poster prompts", "Thumbnail prompts", "Lighting", "Camera direction"],
    restrictions: ["Backend coding", "Database design", "SEO strategy"],
    skillPrompt: SKILL_PROMPTS.gptImage,
  },
  {
    slug: "deep-research",
    name: "Deep Research",
    description: "Produces structured research reports, competitor comparisons, market analysis, and opportunity maps.",
    date: "03/06/2026",
    model: "Loko AI 2.5 Flash",
    modelId: "google/gemini-2.5-flash",
    accent: "from-blue-500 to-sky-500",
    logoText: "DR",
    icon: SearchCheck,
    welcome: "Give me a topic, company, niche, or market and I will turn it into a structured research report.",
    specializations: ["Research", "Competitor comparison", "Market analysis", "Structured reports"],
    restrictions: ["Code implementation", "Image generation", "Personal legal/medical advice"],
    skillPrompt: SKILL_PROMPTS.deepResearch,
  },
  {
    slug: "hook-generator",
    name: "Hook Generator",
    description: "Generates viral hooks, emotional headlines, ad copy, reels hooks, and CTR-focused angles.",
    date: "03/06/2026",
    model: "GPT-4o Mini",
    modelId: "openai/gpt-4o-mini",
    accent: "from-rose-500 to-pink-500",
    logoText: "HG",
    icon: Target,
    welcome: "Share the topic and platform and I will generate short, emotional, curiosity-driven hooks.",
    specializations: ["Hooks", "Headlines", "Ad copy", "Reels hooks", "CTR optimization"],
    restrictions: ["Backend coding", "Database design", "Technical architecture"],
    skillPrompt: SKILL_PROMPTS.hookGenerator,
  },
  {
    slug: "social-media-os",
    name: "Social Media OS",
    description: "Builds platform-first content strategies, reel ideas, captions, retention, and growth systems.",
    date: "03/06/2026",
    model: "Loko AI 2.5 Flash",
    modelId: "google/gemini-2.5-flash",
    accent: "from-purple-500 to-pink-500",
    logoText: "SO",
    icon: Sparkles,
    welcome: "Tell me your niche and platform and I will build a content strategy with captions and growth loops.",
    specializations: ["Content strategy", "Reel ideas", "Captions", "Retention", "Growth systems"],
    restrictions: ["Code implementation", "Database design", "Backend architecture"],
    skillPrompt: SKILL_PROMPTS.socialMediaOs,
  },
  {
    slug: "thumbnail-strategist",
    name: "Thumbnail Strategist",
    description: "Creates high-CTR YouTube thumbnail concepts, visual hierarchy, emotion, and layout prompts.",
    date: "03/06/2026",
    model: "Loko AI 2.5 Flash Image",
    modelId: "google/gemini-2.5-flash-image",
    accent: "from-red-500 to-yellow-500",
    logoText: "TS",
    icon: Camera,
    welcome: "Share the video topic and audience and I will create high-CTR thumbnail concepts.",
    specializations: ["YouTube thumbnails", "CTR", "Visual hierarchy", "Thumbnail prompts"],
    restrictions: ["Backend coding", "Database design", "SEO-only briefs"],
    skillPrompt: SKILL_PROMPTS.thumbnail,
  },
  {
    slug: "design-auditor",
    name: "Design Auditor",
    description: "Audits UI for UX problems, spacing, typography, accessibility, responsiveness, and hierarchy.",
    date: "03/06/2026",
    model: "GPT-4o Mini",
    modelId: "openai/gpt-4o-mini",
    accent: "from-slate-600 to-zinc-500",
    logoText: "DA",
    icon: BrainCircuit,
    welcome: "Describe or share a UI and I will audit hierarchy, spacing, accessibility, and responsiveness.",
    specializations: ["UI audits", "UX problems", "Typography", "Accessibility", "Responsiveness"],
    restrictions: ["Backend architecture", "SEO strategy", "Sales outreach"],
    skillPrompt: SKILL_PROMPTS.designAuditor,
  },
  {
    slug: "voice-builder",
    name: "Voice Builder",
    description: "Develops creator voice, brand personality, tone, style consistency, and audience connection.",
    date: "03/06/2026",
    model: "Kimi K2.6",
    modelId: "moonshotai/kimi-k2.6:free",
    accent: "from-teal-500 to-emerald-500",
    logoText: "VB",
    icon: Bot,
    welcome: "Share your content, audience, or current tone and I will build a clear creator voice profile.",
    specializations: ["Creator voice", "Brand tone", "Writing style", "Communication consistency"],
    restrictions: ["Backend coding", "Database design", "Technical architecture"],
    skillPrompt: SKILL_PROMPTS.voiceBuilder,
  },
  {
    slug: "loko-ai",
    name: "Loko AI",
    description: "Autonomous productivity, workflow planning, execution tracking, and AI workspace coordination.",
    date: "03/06/2026",
    model: "Kimi K2.6",
    modelId: "moonshotai/kimi-k2.6:free",
    accent: "from-emerald-500 to-teal-400",
    logoText: "LA",
    icon: WandSparkles,
    welcome: "Tell me your goals, schedule, or workflow and I will organize execution into a clear system.",
    specializations: ["Productivity", "Task management", "Workflow planning", "Execution tracking", "AI coordination"],
    restrictions: [],
    skillPrompt: SKILL_PROMPTS.lokoAi,
  },
];

export function getAssistant(slug: string) {
  return assistants.find((assistant) => assistant.slug === slug);
}
